services:
  frontend:
    image: voyavox_frontend
    container_name: voyavox_frontend_container
    build:
      context: .
      dockerfile: dockerfile
      args:
        NODE_ENV: production
    ports:
      - "3000:3000"
    environment:
      NEXT_TELEMETRY_DISABLED: "1"
      PORT: 3000
    restart: always
    networks:    # Add this section
      - frontend-network  # Connect the frontend to this network

networks:
  frontend-network:
    name: frontend-network